# Generated by Django 5.1.8 on 2025-06-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_incomplete',
            field=models.BooleanField(default=False),
        ),
    ]
